const SHOW_DATA = 'SHOW_DATA';
const GET_DEPARTMENT = 'GET_DEPARTMENT';
const GET_STATE = 'GET_STATE';
const ADD_DASHBOARD = 'ADD_DASHBOARD';


export {
    SHOW_DATA,
    GET_DEPARTMENT,
    GET_STATE,
    ADD_DASHBOARD
}