const SHOW_DATA = 'SHOW_DATA';
const GET_DEPARTMENT = 'GET_DEPARTMENT';
const GET_STATE = 'GET_STATE';
const ADD_DASHBOARD = 'ADD_DASHBOARD';
const DELETE_DATA = 'DELETE_DATA';
const UPDATE_DASHBOARD = 'UPDATE_DASHBOARD';
const ADD_STATE = 'ADD_STATE';
const UPDATE_PATIENT_STATE = 'UPDATE_PATIENT_STATE';
const LOGIN_USER = 'LOGIN_USER';
const LOAD_USER = 'LOAD_USER';
const LOAD_DASHBOARD = 'LOAD_DASHBOARD';
const LOAD_STATE = 'LOAD_STATE';
const ERROR_AUTH = 'ERROR_AUTH';
const ERROR_DASHBOARD = 'ERROR_DASHBOARD';
const ERROR_STATE = 'ERROR_STATE';
const LOGOUT_USER = 'LOGOUT_USER';

export {
    SHOW_DATA,
    GET_DEPARTMENT,
    GET_STATE,
    ADD_DASHBOARD,
    DELETE_DATA,
    UPDATE_DASHBOARD,
    ADD_STATE,
    UPDATE_PATIENT_STATE,
    LOGIN_USER,
    LOAD_USER,
    LOAD_DASHBOARD,
    LOAD_STATE,
    ERROR_DASHBOARD,
    ERROR_AUTH,
    ERROR_STATE,
    LOGOUT_USER
}